"use client";

import Link from "next/link";
import { useState } from "react";
import {
  Rocket,
  CheckCircle2,
  Copy,
  Terminal,
  ArrowRight,
  ChevronRight,
  Sparkles,
  Code,
  Settings,
  Play,
  FileCode,
  GitBranch,
  Zap,
  BookOpen,
  Clock,
  Users,
  Check,
} from "lucide-react";
import { Footer } from "@/components/layout";

const steps = [
  {
    number: 1,
    title: "Create Your Account",
    description: "Sign up for BetaForge and set up your organization",
    content: `Getting started with BetaForge is simple. Create your free account to access the dashboard and begin setting up your first test project.

1. Visit [betaforge.ai/signup](/signup) and create your account
2. Verify your email address
3. Complete the onboarding questionnaire
4. Set up your organization profile`,
    code: null,
  },
  {
    number: 2,
    title: "Create Your First Project",
    description: "Define your application and testing scope",
    content: `Projects in BetaForge represent individual applications or websites you want to test. Each project can have multiple test sessions with different configurations.`,
    code: `// Example: Creating a project via API
const response = await fetch('https://api.betaforge.ai/v1/projects', {
  method: 'POST',
  headers: {
    'Authorization': 'Bearer YOUR_API_KEY',
    'Content-Type': 'application/json'
  },
  body: JSON.stringify({
    name: 'My Web Application',
    url: 'https://myapp.com',
    description: 'E-commerce platform beta testing',
    platform: 'web'
  })
});

const project = await response.json();
console.log('Project created:', project.id);`,
  },
  {
    number: 3,
    title: "Configure AI Agents",
    description: "Select and customize your testing personas",
    content: `BetaForge provides six unique AI agent personas, each with distinct testing styles and focus areas. Choose agents that match your testing needs.`,
    code: `// Example: Configuring agents for a test session
const agentConfig = {
  agents: [
    {
      id: 'sarah',
      enabled: true,
      focus: ['accessibility', 'ux-clarity']
    },
    {
      id: 'marcus', 
      enabled: true,
      focus: ['performance', 'keyboard-navigation']
    },
    {
      id: 'diego',
      enabled: true,
      focus: ['security', 'error-handling']
    }
  ],
  maxBugsPerAgent: 10,
  sessionDuration: 30 // minutes
};`,
  },
  {
    number: 4,
    title: "Run Your First Test Session",
    description: "Launch AI agents and monitor in real-time",
    content: `Start a test session and watch as AI agents explore your application, identify issues, and generate detailed bug reports.`,
    code: `// Example: Starting a test session
const session = await fetch('https://api.betaforge.ai/v1/sessions', {
  method: 'POST',
  headers: {
    'Authorization': 'Bearer YOUR_API_KEY',
    'Content-Type': 'application/json'
  },
  body: JSON.stringify({
    projectId: 'proj_abc123',
    agents: ['sarah', 'marcus', 'diego'],
    testUrl: 'https://staging.myapp.com',
    duration: 30
  })
});

// Stream real-time updates
const eventSource = new EventSource(
  \`https://api.betaforge.ai/v1/sessions/\${session.id}/stream\`
);

eventSource.onmessage = (event) => {
  const update = JSON.parse(event.data);
  console.log('Agent activity:', update);
};`,
  },
  {
    number: 5,
    title: "Review Bug Reports",
    description: "Analyze AI-generated insights and prioritize fixes",
    content: `Once the test session completes, review the comprehensive bug reports generated by your AI agents. Each report includes detailed reproduction steps, severity ratings, and suggested fixes.`,
    code: `// Example: Fetching bug reports
const reports = await fetch(
  'https://api.betaforge.ai/v1/sessions/sess_xyz789/reports',
  {
    headers: {
      'Authorization': 'Bearer YOUR_API_KEY'
    }
  }
);

const bugs = await reports.json();

// Filter by severity
const criticalBugs = bugs.filter(bug => bug.severity === 'critical');
console.log(\`Found \${criticalBugs.length} critical issues\`);`,
  },
];

const prerequisites = [
  { icon: Globe, text: "A web application or URL to test" },
  { icon: Lock, text: "API key (available in dashboard)" },
  { icon: Code, text: "Basic understanding of REST APIs (optional)" },
];

import { Globe, Lock } from "lucide-react";

export default function GettingStartedPage() {
  const [copiedIndex, setCopiedIndex] = useState<number | null>(null);

  const copyCode = (code: string, index: number) => {
    navigator.clipboard.writeText(code);
    setCopiedIndex(index);
    setTimeout(() => setCopiedIndex(null), 2000);
  };

  return (
    <div className="min-h-screen bg-void-black">
      {/* Background */}
      <div className="fixed inset-0 pointer-events-none">
        <div className="absolute inset-0 mesh-bg opacity-30" />
        <div className="absolute top-0 left-1/4 w-[500px] h-[500px] bg-neural/10 rounded-full blur-[120px]" />
        <div className="absolute bottom-1/4 right-0 w-[400px] h-[400px] bg-quantum-green/10 rounded-full blur-[100px]" />
      </div>

      {/* Header */}
      <header className="fixed top-0 left-0 right-0 z-50 border-b border-white/5 bg-void-black/80 backdrop-blur-xl">
        <div className="max-w-7xl mx-auto px-6 py-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-8">
              <Link href="/" className="flex items-center gap-3">
                <div className="relative w-10 h-10 rounded-xl bg-gradient-to-br from-neural-bright to-electric-cyan flex items-center justify-center">
                  <Sparkles className="w-5 h-5 text-white" />
                </div>
                <span className="text-xl font-bold gradient-text">
                  BetaForge
                </span>
              </Link>
              <nav className="hidden md:flex items-center">
                <Link
                  href="/docs"
                  className="text-phantom-gray hover:text-ghost-white text-sm transition-colors px-3 py-2"
                >
                  Docs
                </Link>
                <ChevronRight className="w-4 h-4 text-mist-gray" />
                <span className="text-ghost-white text-sm px-3 py-2">
                  Getting Started
                </span>
              </nav>
            </div>
            <Link
              href="/dashboard"
              className="px-4 py-2 rounded-lg bg-neural/20 text-ghost-white text-sm font-medium hover:bg-neural/30 transition-colors"
            >
              Dashboard
            </Link>
          </div>
        </div>
      </header>

      {/* Hero Section */}
      <section className="relative pt-32 pb-16 px-6">
        <div className="max-w-4xl mx-auto">
          <div className="flex items-center gap-2 text-sm text-phantom-gray mb-6">
            <Link
              href="/docs"
              className="hover:text-ghost-white transition-colors"
            >
              Documentation
            </Link>
            <ChevronRight className="w-4 h-4" />
            <span className="text-ghost-white">Getting Started</span>
          </div>

          <div className="flex items-center gap-4 mb-6">
            <div className="p-4 rounded-2xl bg-gradient-to-br from-quantum-green/20 to-electric-cyan/20 border border-quantum-green/20">
              <Rocket className="w-8 h-8 text-quantum-green" />
            </div>
            <div>
              <h1 className="text-4xl md:text-5xl font-bold text-ghost-white">
                Getting Started
              </h1>
              <div className="flex items-center gap-4 mt-2 text-sm text-phantom-gray">
                <span className="flex items-center gap-1">
                  <Clock className="w-4 h-4" />5 min read
                </span>
                <span className="flex items-center gap-1">
                  <BookOpen className="w-4 h-4" />
                  Beginner
                </span>
              </div>
            </div>
          </div>

          <p className="text-lg text-phantom-gray leading-relaxed mb-8">
            Welcome to BetaForge! This guide will walk you through setting up
            your account, creating your first project, and running AI-powered
            tests on your application. In just a few minutes, you&apos;ll have
            autonomous AI agents testing your software.
          </p>

          {/* Prerequisites */}
          <div className="p-6 bg-void-elevated border border-white/5 rounded-2xl mb-12">
            <h3 className="text-lg font-semibold text-ghost-white mb-4 flex items-center gap-2">
              <CheckCircle2 className="w-5 h-5 text-quantum-green" />
              Prerequisites
            </h3>
            <ul className="space-y-3">
              {prerequisites.map((prereq, index) => (
                <li
                  key={index}
                  className="flex items-center gap-3 text-phantom-gray"
                >
                  <prereq.icon className="w-4 h-4 text-neural-bright" />
                  <span>{prereq.text}</span>
                </li>
              ))}
            </ul>
          </div>
        </div>
      </section>

      {/* Steps Section */}
      <section className="relative py-12 px-6">
        <div className="max-w-4xl mx-auto">
          <div className="space-y-16">
            {steps.map((step, index) => (
              <div key={index} className="relative">
                {/* Connector Line */}
                {index < steps.length - 1 && (
                  <div className="absolute left-6 top-16 bottom-0 w-px bg-gradient-to-b from-neural/50 to-transparent" />
                )}

                <div className="flex gap-6">
                  {/* Step Number */}
                  <div className="flex-shrink-0">
                    <div className="w-12 h-12 rounded-xl bg-gradient-to-br from-neural to-electric-cyan flex items-center justify-center text-white font-bold text-lg">
                      {step.number}
                    </div>
                  </div>

                  {/* Step Content */}
                  <div className="flex-1">
                    <h2 className="text-2xl font-bold text-ghost-white mb-2">
                      {step.title}
                    </h2>
                    <p className="text-phantom-gray mb-6">{step.description}</p>

                    <div className="prose prose-invert max-w-none mb-6">
                      <p className="text-phantom-gray leading-relaxed whitespace-pre-line">
                        {step.content}
                      </p>
                    </div>

                    {step.code && (
                      <div className="relative">
                        <div className="flex items-center justify-between px-4 py-2 bg-void-black border border-white/10 rounded-t-xl">
                          <div className="flex items-center gap-2">
                            <FileCode className="w-4 h-4 text-mist-gray" />
                            <span className="text-xs text-mist-gray">
                              JavaScript
                            </span>
                          </div>
                          <button
                            onClick={() => copyCode(step.code!, index)}
                            className="flex items-center gap-1 text-xs text-phantom-gray hover:text-ghost-white transition-colors"
                          >
                            {copiedIndex === index ? (
                              <>
                                <Check className="w-3 h-3 text-quantum-green" />
                                <span className="text-quantum-green">
                                  Copied!
                                </span>
                              </>
                            ) : (
                              <>
                                <Copy className="w-3 h-3" />
                                <span>Copy</span>
                              </>
                            )}
                          </button>
                        </div>
                        <pre className="p-4 bg-void-elevated border border-t-0 border-white/10 rounded-b-xl overflow-x-auto">
                          <code className="text-sm text-phantom-gray font-mono">
                            {step.code}
                          </code>
                        </pre>
                      </div>
                    )}
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Next Steps */}
      <section className="relative py-20 px-6">
        <div className="max-w-4xl mx-auto">
          <h2 className="text-3xl font-bold text-ghost-white mb-8">
            What&apos;s Next?
          </h2>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <Link
              href="/docs/agents"
              className="group p-6 bg-void-elevated border border-white/5 rounded-2xl hover:border-neural/30 transition-all"
            >
              <div className="flex items-center gap-4 mb-3">
                <Users className="w-6 h-6 text-neural-bright" />
                <h3 className="text-lg font-semibold text-ghost-white group-hover:text-neural-bright transition-colors">
                  Explore AI Agents
                </h3>
              </div>
              <p className="text-sm text-phantom-gray">
                Learn about each agent persona and how to configure them for
                your needs.
              </p>
            </Link>
            <Link
              href="/docs/api"
              className="group p-6 bg-void-elevated border border-white/5 rounded-2xl hover:border-neural/30 transition-all"
            >
              <div className="flex items-center gap-4 mb-3">
                <Code className="w-6 h-6 text-electric-cyan" />
                <h3 className="text-lg font-semibold text-ghost-white group-hover:text-neural-bright transition-colors">
                  API Reference
                </h3>
              </div>
              <p className="text-sm text-phantom-gray">
                Dive into the complete API documentation for advanced
                integrations.
              </p>
            </Link>
            <Link
              href="/docs/integrations"
              className="group p-6 bg-void-elevated border border-white/5 rounded-2xl hover:border-neural/30 transition-all"
            >
              <div className="flex items-center gap-4 mb-3">
                <GitBranch className="w-6 h-6 text-plasma-pink" />
                <h3 className="text-lg font-semibold text-ghost-white group-hover:text-neural-bright transition-colors">
                  CI/CD Integration
                </h3>
              </div>
              <p className="text-sm text-phantom-gray">
                Set up automated testing in your deployment pipeline.
              </p>
            </Link>
            <Link
              href="/docs/sessions/reports"
              className="group p-6 bg-void-elevated border border-white/5 rounded-2xl hover:border-neural/30 transition-all"
            >
              <div className="flex items-center gap-4 mb-3">
                <Zap className="w-6 h-6 text-quantum-green" />
                <h3 className="text-lg font-semibold text-ghost-white group-hover:text-neural-bright transition-colors">
                  Understanding Reports
                </h3>
              </div>
              <p className="text-sm text-phantom-gray">
                Learn how to interpret and act on AI-generated bug reports.
              </p>
            </Link>
          </div>
        </div>
      </section>

      <Footer />
    </div>
  );
}
